### ISSUE TITLE
Fix wording of contact-us confirmation

### ISSUE THREAD

**Issue by jens-woodlore** [Rockwynn/staging.woodlore.ca#6]
Contact-us confirmation is probably incorrect. It was probably meant to read 

> Thanks we'll be in touch as soon as (super)humanly possible!

![image](https://user-images.githubusercontent.com/57366234/68973361-16716e00-07bc-11ea-8ee8-04e94b1019e4.png)

**Comment by 3piecewise** [comment]
Fixed sentence.
