### ISSUE TITLE
Inconsistent layout for special quotes email

### ISSUE THREAD

**Issue by jens-woodlore** [Rockwynn/staging.woodlore.ca#8]
On the contact us page, the special quotes email address is on a separate line from the `Email:` label but should be on the same line as in the general information above it.

![image](https://user-images.githubusercontent.com/57366234/69348221-d4c14700-0c43-11ea-877f-8bbc02ab9980.png)

**Comment by 3piecewise** [comment]
Wrote code to reflect desired outcome.
